name: autofix.ci

on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npx prettier --write ./src ./public

      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
